version: '3'

services:
  reverse-proxy:
    image: traefik:v2.9
    command: 
      - --api.insecure=true 
      - --providers.docker
      - --providers.file.filename=/config/dynamic_conf.yml
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/traefik:/config
      - ./secrets/ssl:/ssl

