tls:
  options:
    default:
      clientAuth:
        caFiles:
          - /etc/traefik/authenticated_origin_pull_ca.pem
        clientAuthType: RequireAndVerifyClientCert
  stores:
    default:
      defaultCertificate:
        certFile: /ssl/cert.pem
        keyFile: /ssl/key.pem