version: '3'

services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy:0.1
    restart: unless-stopped
    userns_mode: 'host'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
    networks:
      - docker-proxynet

  reverse-proxy:
    image: traefik:v2.9
    restart: unless-stopped
    read_only: true
    depends_on:
      - dockerproxy
    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      # Dashboard
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=web-secure
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD_HASH}
    volumes:
      - ./conf/traefik/traefik.yml:/etc/traefik/traefik.yaml:ro
      - ./conf/traefik/authenticated_origin_pull_ca.pem:/etc/traefik/authenticated_origin_pull_ca.pem:ro
      - ./conf/traefik/dynamic:/etc/traefik/dynamic:ro
      - ./secrets/ssl:/ssl:ro
    networks:
      - traefik-servicenet
      - docker-proxynet
    ports:
      - "80:80"
      - "443:443"

networks:
  traefik-servicenet:
    external: true
    name: traefik-servicenet
 
  docker-proxynet:
    driver: bridge
    internal: true